### ISSUE TITLE
Latest 10 Bug && 优化建议

### ISSUE THREAD

**Issue by Wnltc** [leesinz/Athena#3]
Bug ：
>Latest 10 漏洞查询有个小bug，查出来的结果并不是全是最近更新的10条，vuls页面查出来的也是，两边都不完全按最近更新时间来输出

建议：
>把数据库中的date类型改成datetime，这样记录到的信息能更详细点，使用datetime DEFAULT CURRENT_TIMESTAMP可以在入库时自动记录时间
>前端显示时，建议也把时间详细到秒，可以看起来更清晰点
<img width="1295" alt="image" src="https://github.com/user-attachments/assets/5bf7774a-4b1d-4898-b2d1-e56ba5ccd124">
<img width="1272" alt="image" src="https://github.com/user-attachments/assets/c5cc292f-506e-490e-9f72-fbd6b0a4c272">
<img width="931" alt="image" src="https://github.com/user-attachments/assets/e5d58b5e-226b-4fef-9f94-c28976c69036">

**Comment by leesinz** [comment]
后续更新会更新date字段的类型，并优化前端显示
感谢~

**Comment by leesinz** [comment]
在v2.0.2中已完成修改
