### ISSUE TITLE
> 你说的问题是指飞书bot不加签名校验导致的吗

### ISSUE THREAD

**Issue by leesinz** [leesinz/Athena#7]
> 你说的问题是指飞书bot不加签名校验导致的吗

不是，那个content是个JSON字符串，不是JSON，要转换一下，我PR给你改了

_Originally posted by @MagakiReimu in https://github.com/leesinz/Athena/issues/4#issuecomment-2272753994_

**Comment by leesinz** [comment]
飞书bot我本地测试能够正常运行，晚点我再看下

**Comment by LoopOuroboros** [comment]
那可能飞书那边改了，应用机器人那边都是JSON字符串，要转换的，PR那边飞书的那个机器人不需要加密最好还是也支持一下

**Comment by leesinz** [comment]
ok~
